apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dbt-date
  title: dbt-date
  description: dbt macro package for date logic and calendar functionality.
  annotations:
    github.com/project-slug: hipagesgroup/dbt-date
    github.com/team-slug: data-analytics-engineering
    backstage.io/techdocs-ref: dir:../
  tags:
    - repo
    - dbt
    - sql
spec:
  domain: data-analytics
  owner: data-analytics-engineering
  lifecycle: production
